'use client';

import { useState, useEffect } from 'react';
import { Header } from '@/components/Header';
import { Heart, RefreshCw, User, BookOpen } from 'lucide-react';
import Image from 'next/image';
import { useAuth } from '@/context/AuthContext';

interface GalleryItem {
  id: string;
  imageUrl: string;
  prompt: string;
  userName: string;
  catalogName: string;
  userId?: string;
  isFavorite: boolean;
  createdAt: string;
}

export default function GalleryPage() {
  const [items, setItems] = useState<GalleryItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [filter, setFilter] = useState<'favorites' | 'all'>('all');
  const { user } = useAuth();

  const fetchGallery = async () => {
    setLoading(true);
    try {
      const res = await fetch('/api/gallery');
      if (res.ok) {
        const data = await res.json();
        setItems(data.items);
      }
    } catch (e) {
      console.error('Failed to fetch gallery items', e);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchGallery();
  }, []);

  const toggleFavorite = async (id: string) => {
    // Optimistic update
    setItems(items.map(item => item.id === id ? { ...item, isFavorite: !item.isFavorite } : item));
    
    try {
      await fetch(`/api/gallery/${id}/favorite`, { method: 'POST' });
    } catch (e) {
      console.error('Failed to toggle favorite', e);
      // Revert on failure
      fetchGallery();
    }
  };

  const currentUserId = user?.id || 'anonymous';

  const displayedItems = items.filter(i => {
    // Only show images generated by the current user
    const isMine = i.userId === currentUserId || (currentUserId === 'anonymous' && i.userName === 'Anonymous Artist');
    if (!isMine) return false;
    
    if (filter === 'favorites') return i.isFavorite;
    return true;
  });

  return (
    <div className="min-h-screen bg-zinc-950 text-white">
      <Header />
      <main className="max-w-7xl mx-auto p-8">
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-8 gap-4">
          <div>
            <h1 className="text-4xl font-bold mb-2">My Gallery</h1>
            <p className="text-zinc-400">View the images you have generated and your personal favorites.</p>
          </div>
          
          <div className="flex items-center gap-4">
            <div className="flex bg-zinc-900 rounded-lg p-1 border border-zinc-800">
              <button 
                onClick={() => setFilter('all')}
                className={`px-4 py-2 rounded-md text-sm font-medium transition-colors ${filter === 'all' ? 'bg-zinc-800 text-white' : 'text-zinc-400 hover:text-zinc-300'}`}
              >
                My Generations
              </button>
              <button 
                onClick={() => setFilter('favorites')}
                className={`px-4 py-2 rounded-md text-sm font-medium flex items-center gap-2 transition-colors ${filter === 'favorites' ? 'bg-zinc-800 text-white' : 'text-zinc-400 hover:text-zinc-300'}`}
              >
                <Heart className="w-4 h-4" /> My Favorites
              </button>
            </div>
            <button 
              onClick={fetchGallery}
              className="flex items-center gap-2 bg-zinc-800 hover:bg-zinc-700 px-4 py-2 rounded-lg border border-zinc-700 transition-colors"
            >
              <RefreshCw className={`w-4 h-4 ${loading ? 'animate-spin' : ''}`} />
            </button>
          </div>
        </div>

        {/* Gallery Grid */}
        {loading && items.length === 0 ? (
          <div className="text-center py-20 text-zinc-500">Loading gallery...</div>
        ) : displayedItems.length === 0 ? (
          <div className="text-center py-20 bg-zinc-900/30 rounded-xl border border-dashed border-zinc-800">
            <h3 className="text-xl font-medium text-zinc-400 mb-2">No images found</h3>
            <p className="text-zinc-500">Generate some images in the Studio to see them here.</p>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
            {displayedItems.map((item) => (
              <div key={item.id} className="group bg-zinc-900 rounded-xl overflow-hidden border border-zinc-800 hover:border-zinc-700 transition-all hover:shadow-xl hover:shadow-black/50">
                <div className="relative aspect-square bg-zinc-950 overflow-hidden">
                  {item.imageUrl.startsWith('<svg') ? (
                    <div className="w-full h-full" dangerouslySetInnerHTML={{ __html: item.imageUrl }} />
                  ) : (
                    <Image 
                      src={item.imageUrl} 
                      alt={item.prompt}
                      fill
                      className="object-cover transition-transform duration-500 group-hover:scale-105"
                      sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 25vw"
                      unoptimized={item.imageUrl.startsWith('blob:')}
                    />
                  )}
                  <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity flex flex-col justify-end p-4">
                    <button 
                      onClick={(e) => { e.preventDefault(); toggleFavorite(item.id); }}
                      className={`absolute top-4 right-4 p-2 rounded-full backdrop-blur-md transition-colors ${item.isFavorite ? 'bg-red-500/20 text-red-500 hover:bg-red-500/30' : 'bg-black/40 text-white hover:bg-black/60'}`}
                      title={item.isFavorite ? "Remove from favorites" : "Add to favorites"}
                    >
                      <Heart className={`w-5 h-5 ${item.isFavorite ? 'fill-current' : ''}`} />
                    </button>
                    <p className="text-sm text-zinc-200 line-clamp-2">{item.prompt}</p>
                  </div>
                </div>
                
                <div className="p-4 border-t border-zinc-800">
                  <div className="flex items-center gap-2 mb-2 text-zinc-300">
                    <User className="w-4 h-4 text-zinc-500" />
                    <span className="font-medium text-sm truncate">{item.userName}</span>
                  </div>
                  <div className="flex items-center gap-2 text-zinc-400">
                    <BookOpen className="w-4 h-4 text-zinc-500" />
                    <span className="text-xs truncate">{item.catalogName}</span>
                  </div>
                  <div className="mt-3 flex justify-between items-center text-xs text-zinc-500">
                    <span>{new Date(item.createdAt).toLocaleDateString()}</span>
                    {item.isFavorite && <span className="text-red-400 font-medium">Favorite</span>}
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}
      </main>
    </div>
  );
}