'use client';

import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { Header } from '@/components/Header';
import { Heart, RefreshCw, User, BookOpen, Eye, ShoppingCart, Zap, Nfc, Sparkles } from 'lucide-react';
import { useAuth } from '@/context/AuthContext';

interface GalleryItem {
  id: string;
  imageUrl: string;
  prompt: string;
  userName: string;
  catalogName: string;
  userId?: string;
  deviceId?: string;
  isFavorite: boolean;
  createdAt: string;
  isQuantumVerified?: boolean;
  isNft?: boolean;
  nftId?: string;
}

export default function GalleryPage() {
  const router = useRouter();
  const [items, setItems] = useState<GalleryItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [filter, setFilter] = useState<'favorites' | 'all' | 'nfts' | 'quantum'>('all');
  const { user } = useAuth();
  const [deviceId, setDeviceId] = useState<string>('');

  const fetchGallery = async () => {
    setLoading(true);
    try {
      const res = await fetch('/api/gallery');
      if (res.ok) {
        const data = await res.json();
        const serverItems = Array.isArray(data.items) ? data.items : [];

        const cacheKey = 'ft.gallery.cache';
        const cachedRaw = typeof window !== 'undefined' ? localStorage.getItem(cacheKey) : null;
        const cached = cachedRaw ? JSON.parse(cachedRaw) : [];
        const cachedItems = Array.isArray(cached) ? cached : [];

        const byId = new Map<string, GalleryItem>();
        for (const it of [...cachedItems, ...serverItems]) {
          if (it && typeof it.id === 'string') byId.set(it.id, it as GalleryItem);
        }
        setItems(Array.from(byId.values()));
      }
    } catch (e) {
      console.error('Failed to fetch gallery items', e);
      try {
        const cacheKey = 'ft.gallery.cache';
        const cachedRaw = localStorage.getItem(cacheKey);
        const cached = cachedRaw ? JSON.parse(cachedRaw) : [];
        setItems(Array.isArray(cached) ? cached : []);
      } catch {}
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    try {
      let id = localStorage.getItem('device_id');
      if (!id) {
        id = `dev_${Date.now()}_${Math.random().toString(36).slice(2, 10)}`;
        localStorage.setItem('device_id', id);
      }
      setDeviceId(id);
    } catch {}
    fetchGallery();
  }, []);

  const toggleFavorite = async (id: string) => {
    // Optimistic update
    setItems(items.map(item => item.id === id ? { ...item, isFavorite: !item.isFavorite } : item));
    
    try {
      await fetch(`/api/gallery/${id}/favorite`, { method: 'POST' });
    } catch (e) {
      console.error('Failed to toggle favorite', e);
      // Revert on failure
      fetchGallery();
    }
  };

  const currentUserId = user?.id || 'anonymous';

  const displayedItems = items.filter(i => {
    // Only show images generated by the current user
    const isMine =
      i.userId === currentUserId ||
      (!!deviceId && i.deviceId === deviceId) ||
      (currentUserId === 'anonymous' && i.userName === 'Anonymous Artist');
    if (!isMine) return false;
    
    if (filter === 'favorites') return i.isFavorite;
    if (filter === 'nfts') return !!i.isNft;
    if (filter === 'quantum') return !!i.isQuantumVerified;
    return true;
  });

  return (
    <div className="min-h-screen bg-zinc-950 text-white">
      <Header />
      <main className="max-w-7xl mx-auto p-8">
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-8 gap-4">
          <div>
            <h1 className="text-4xl font-bold mb-2">My Gallery</h1>
            <p className="text-zinc-400">View the images you have generated, your favorites, NFTs, and Quantum Verified items.</p>
          </div>
          
          <div className="flex items-center gap-4">
            <div className="flex bg-zinc-900 rounded-lg p-1 border border-zinc-800 flex-wrap">
              <button 
                onClick={() => setFilter('all')}
                className={`px-4 py-2 rounded-md text-sm font-medium transition-colors ${filter === 'all' ? 'bg-zinc-800 text-white' : 'text-zinc-400 hover:text-zinc-300'}`}
              >
                My Generations
              </button>
              <button 
                onClick={() => setFilter('favorites')}
                className={`px-4 py-2 rounded-md text-sm font-medium flex items-center gap-2 transition-colors ${filter === 'favorites' ? 'bg-zinc-800 text-white' : 'text-zinc-400 hover:text-zinc-300'}`}
              >
                <Heart className="w-4 h-4" /> My Favorites
              </button>
              <button 
                onClick={() => setFilter('nfts')}
                className={`px-4 py-2 rounded-md text-sm font-medium flex items-center gap-2 transition-colors ${filter === 'nfts' ? 'bg-zinc-800 text-white' : 'text-zinc-400 hover:text-zinc-300'}`}
              >
                <Nfc className="w-4 h-4" /> My NFTs
              </button>
              <button 
                onClick={() => setFilter('quantum')}
                className={`px-4 py-2 rounded-md text-sm font-medium flex items-center gap-2 transition-colors ${filter === 'quantum' ? 'bg-zinc-800 text-white' : 'text-zinc-400 hover:text-zinc-300'}`}
              >
                <Zap className="w-4 h-4" /> Quantum Verified
              </button>
            </div>
            <button 
              onClick={fetchGallery}
              className="flex items-center gap-2 bg-zinc-800 hover:bg-zinc-700 px-4 py-2 rounded-lg border border-zinc-700 transition-colors"
            >
              <RefreshCw className={`w-4 h-4 ${loading ? 'animate-spin' : ''}`} />
            </button>
          </div>
        </div>

        {/* Gallery Grid */}
        {loading && items.length === 0 ? (
          <div className="text-center py-20 text-zinc-500">Loading gallery...</div>
        ) : displayedItems.length === 0 ? (
          <div className="text-center py-20 bg-zinc-900/30 rounded-xl border border-dashed border-zinc-800">
            <h3 className="text-xl font-medium text-zinc-400 mb-2">No items found</h3>
            <p className="text-zinc-500">
              {filter === 'all' ? 'Generate some images in the Studio to see them here.' :
               filter === 'favorites' ? 'Mark some images as favorites to see them here.' :
               filter === 'nfts' ? 'Create some NFTs to see them here.' :
               'Generate some Quantum Verified images to see them here.'}
            </p>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
            {displayedItems.map((item) => (
              <div key={item.id} className="group bg-zinc-900 rounded-xl overflow-hidden border border-zinc-800 hover:border-zinc-700 transition-all hover:shadow-xl hover:shadow-black/50">
                <div className="relative aspect-square bg-zinc-950 overflow-hidden">
                  {item.isQuantumVerified && (
                    <div className="absolute top-4 left-4 z-10 bg-purple-500/80 backdrop-blur-sm text-white px-3 py-1 rounded-full text-xs font-semibold flex items-center gap-1">
                      <Zap className="w-3 h-3" /> Quantum Verified
                    </div>
                  )}
                  {item.isNft && (
                    <div className="absolute top-4 left-4 z-10 bg-green-500/80 backdrop-blur-sm text-white px-3 py-1 rounded-full text-xs font-semibold flex items-center gap-1 ml-32">
                      <Nfc className="w-3 h-3" /> NFT
                    </div>
                  )}
                  {item.imageUrl.startsWith('<svg') ? (
                    <div className="w-full h-full" dangerouslySetInnerHTML={{ __html: item.imageUrl }} />
                  ) : (
                    <img
                      src={item.imageUrl}
                      alt={item.prompt}
                      className="absolute inset-0 h-full w-full object-cover transition-transform duration-500 group-hover:scale-105"
                      loading="lazy"
                    />
                  )}
                  <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity flex flex-col justify-end p-4">
                    <button 
                      onClick={(e) => { e.preventDefault(); toggleFavorite(item.id); }}
                      className={`absolute top-4 right-4 p-2 rounded-full backdrop-blur-md transition-colors ${item.isFavorite ? 'bg-red-500/20 text-red-500 hover:bg-red-500/30' : 'bg-black/40 text-white hover:bg-black/60'}`}
                      title={item.isFavorite ? "Remove from favorites" : "Add to favorites"}
                    >
                      <Heart className={`w-5 h-5 ${item.isFavorite ? 'fill-current' : ''}`} />
                    </button>
                    <p className="text-sm text-zinc-200 line-clamp-2">{item.prompt}</p>
                  </div>
                </div>
                
                <div className="p-4 border-t border-zinc-800">
                  <div className="flex items-center gap-2 mb-2 text-zinc-300">
                    <User className="w-4 h-4 text-zinc-500" />
                    <span className="font-medium text-sm truncate">{item.userName}</span>
                  </div>
                  <div className="flex items-center gap-2 text-zinc-400 mb-3">
                    <BookOpen className="w-4 h-4 text-zinc-500" />
                    <span className="text-xs truncate">{item.catalogName}</span>
                  </div>
                  <div className="flex gap-2 mb-3">
                    <button 
                      onClick={() => router.push('/customize')}
                      className="flex-1 flex items-center justify-center gap-2 bg-zinc-800 hover:bg-zinc-700 text-zinc-200 px-3 py-2 rounded-lg text-sm transition-colors"
                    >
                      <Eye className="w-4 h-4" /> Preview
                    </button>
                    <button 
                      onClick={() => router.push('/cart')}
                      className="flex-1 flex items-center justify-center gap-2 bg-blue-600 hover:bg-blue-500 text-white px-3 py-2 rounded-lg text-sm transition-colors"
                    >
                      <ShoppingCart className="w-4 h-4" /> Purchase
                    </button>
                  </div>
                  <div className="flex justify-between items-center text-xs text-zinc-500">
                    <span>{new Date(item.createdAt).toLocaleDateString()}</span>
                    <div className="flex items-center gap-2">
                      {item.isFavorite && <span className="text-red-400 font-medium">Favorite</span>}
                      {item.isQuantumVerified && <span className="text-purple-400 font-medium">Quantum</span>}
                      {item.isNft && <span className="text-green-400 font-medium">NFT</span>}
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}
      </main>
    </div>
  );
}
